name: github pages

on:
  push:
    branches:
      - main # default branch

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - uses: actions/checkout@v2
      - run: node -v
      - run: npm i
      - run: npm run build:gh
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
